spring:
  application:
    name: game-niuniu-tb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: GMT+8
  redis:
    host: 192.168.1.57
    database: 7
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 30000
        min-idle: 1
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://sec_game:1qaz2wsx@192.168.1.96:20000,192.168.1.97:20000,192.168.1.98:20000
      database: game
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: game_center_app
    password: Jxinternet@1234
    url: jdbc:mysql://192.168.1.93:3306/gcenter?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true
#ribbon:
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  OkToRetryOnAllOperations: true
#  ConnectTimeout: 5000
#

server:
  port: 8095

feign:
  hystrix:
    enabled: false

logging:
#  level:
#    com.jxinternet.platform: debug
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus

rocket:
  namesrv-address: 192.168.1.157:9876;192.168.1.158:9876
  consumer-group: niuniu_tb_consumer_group
  consumer-topic: cg_niuniu_tb_in
  producer-group: niuniu_tb_producer_group
  producer-topic: cg_niuniu_tb_out

#druid:
#  type: com.alibaba.druid.pool.DruidDataSource
#  master:
#    url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: sec_balance
#    password: Jxinternet@1234
#  slave:
#    url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: sec_balance
#    password: Jxinternet@1234


customer:
  datasource:
    gCenter:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/gcenter?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: game_center_app
      password: Jxinternet@1234
    masterDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234
    slaveDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234

game:
  id: 20
  name: 通比牛牛
