spring:
  application:
    name: game-luck-app
  profiles:
    active: pro
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: GMT+8
  redis:
    host: 192.168.1.57
    database: 7
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 30000
        min-idle: 1
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://sec_game:1qaz2wsx@192.168.1.96:20000,192.168.1.97:20000,192.168.1.98:20000
      database: game
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: game_center_app
    password: Jxinternet@1234
    url: jdbc:mysql://192.168.1.93:3306/gcenter?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true

logging:
  config: classpath:logback-spring.xml

server:
  port: 8098

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus

rocket:
  namesrv-address: 192.168.1.157:9876;192.168.1.158:9876
  consumer-group: xywz_consumer_group
  consumer-topic: cg_xywz_in
  producer-group: xywz_producer_group
  producer-topic: cg_xywz_out
  system_group: game_interior_consumer_group
  system_topic: game_interior_in

customer:
  datasource:
    gCenter:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/gcenter?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: game_center_app
      password: Jxinternet@1234
    masterDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234
    slaveDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234

game:
  id: 28
  name: 幸运五张
  table-cache-second: 900
  version: 'V1'
  risk_enabled: true
  max-table-cycle-seconds: 300
  bet_timeout: 18000
  size_timeout: 24000
  wait_size_timeout: 27000
  exchange_timeout: 20000
  wait_exchange_timeout: 5000
  confModel:
    time:
      section: "10m"
      prefix: "0m"
    range:
      - start: -100
        end: -10 
        rate: 100
        result: 1
      - start: -10
        end: 0
        rate: 80
        result: 1
      - start: 0
        end: 3
        rate: 100
        result: 0
      - start: 3
        end: 10
        rate: 80
        result: -1
      - start: 10
        end: 100
        rate: 100
        result: -1
  match:
    wait-queue-capacity: 50
    threads: 2
    max-wait-seconds: 1
    max-person: 1
  timeout:
    wait-queue-capacity: 100
    threads: 2
    batch-tasks: 5
  api:
     enable-inner-version: true # 日志开关  sit 为true  uat 以及 线上请设置成false
