spring:
  application:
    name: game-fish-app
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: GMT+8
  redis:
    host: 192.168.1.57
    port: 6379
    database: 7
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: 8000
        min-idle: 30
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://sec_game:1qaz2wsx@192.168.1.96:20000,192.168.1.97:20000,192.168.1.98:20000
      database: game
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: game_center_app
    password: Jxinternet@1234
    url: jdbc:mysql://192.168.1.93:3306/gcenter?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:logback-spring.xml

server:
  port: 8114

feign:
  hystrix:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus

rocket:
  namesrv-address: 192.168.1.157:9876;192.168.1.158:9876
  consumer-group: fishing_consumer_group
  consumer-topic: cg_fishing_in
  producer-group: fishing_producer_group
  producer-topic: cg_fishing_out
  system_group: game_interior_consumer_group
  system_topic: game_interior_in

customer:
  datasource:
    gCenter:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/gcenter?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: game_center_app
      password: Jxinternet@1234
    masterDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234
    slaveDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234  
game:
  id: '90'
  name: 'fishing'
  table-cache-second: 900
  max-table-cycle-seconds: 200
  fish-info_time: 100
  shot-time: 120
  barbette-time: 10000

  match:
    wait-queue-capacity: 50
    threads: 2
    max-wait-seconds: 3
    max-person: 4
  timeout:
    wait-queue-capacity: 100
    threads: 2
    batch-tasks: 5
  api:
    enable-inner-version: true

monitor:
  player:
    expired-enabled: true
    expire-seconds: 180
    error-code: 90201
