var games = [
{
    "_id": NumberInt(377),
    "name": "FG-摸金校尉",
    "alias": "fg-mjxw",
    "icon": "/common/gameIcon/fg/mobile/mjxw.png",
    "url": "../mjxw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1967),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mjxw",
    "classifyAlias" : "fg-mjxw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mjxw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(378),
    "name": "FG-埃及艳后",
    "alias": "fg-mny",
    "icon": "/common/gameIcon/fg/mobile/mny.png",
    "url": "../mny/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1968),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mny",
    "classifyAlias" : "fg-mny", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mny.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(379),
    "name": "FG-泰坦尼克号",
    "alias": "fg-mtitanic",
    "icon": "/common/gameIcon/fg/mobile/mtitanic.png",
    "url": "../mtitanic/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1969),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mtitanic",
    "classifyAlias" : "fg-mtitanic", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mtitanic.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(380),
    "name": "FG-玛雅",
    "alias": "fg-my",
    "icon": "/common/gameIcon/fg/mobile/my.png",
    "url": "../my/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1970),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "my",
    "classifyAlias" : "fg-my", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/my.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(381),
    "name": "FG-梦游仙境",
    "alias": "fg-myxj",
    "icon": "/common/gameIcon/fg/mobile/myxj.png",
    "url": "../myxj/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1972),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "myxj",
    "classifyAlias" : "fg-myxj", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/myxj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(382),
    "name": "FG-鸟叔",
    "alias": "fg-mpjs",
    "icon": "/common/gameIcon/fg/mobile/ns.png",
    "url": "../mpjs/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1973),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mpjs",
    "classifyAlias" : "fg-mpjs", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ns.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(383),
    "name": "FG-女校橄榄球",
    "alias": "fg-nxglq",
    "icon": "/common/gameIcon/fg/mobile/nxglq.png",
    "url": "../nxglq/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1974),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "nxglq",
    "classifyAlias" : "fg-nxglq", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nxglq.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(384),
    "name": "FG-女校剑道",
    "alias": "fg-nxjdb",
    "icon": "/common/gameIcon/fg/mobile/nxjd.png",
    "url": "../nxjdb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1975),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "nxjdb",
    "classifyAlias" : "fg-nxjdb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nxjd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(385),
    "name": "FG-女校体操队",
    "alias": "fg-sgt",
    "icon": "/common/gameIcon/fg/mobile/nxtcd.png",
    "url": "../sgt/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1976),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "sgt",
    "classifyAlias" : "fg-sgt", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nxtcd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(386),
    "name": "FG-女校游泳队",
    "alias": "fg-sst",
    "icon": "/common/gameIcon/fg/mobile/nxyyd.png",
    "url": "../sst/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1977),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "sst",
    "classifyAlias" : "fg-sst", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nxyyd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(387),
    "name": "FG-新年",
    "alias": "fg-ny",
    "icon": "/common/gameIcon/fg/mobile/ny.png",
    "url": "../ny/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1978),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "ny",
    "classifyAlias" : "fg-ny", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ny.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(388),
    "name": "FG-闹元宵",
    "alias": "fg-mnys",
    "icon": "/common/gameIcon/fg/mobile/nyx.png",
    "url": "../mnys/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1979),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mnys",
    "classifyAlias" : "fg-mnys", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nyx.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(389),
    "name": "FG-荒野大镖客",
    "alias": "fg-nz2",
    "icon": "/common/gameIcon/fg/mobile/nz2.png",
    "url": "../nz2/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1980),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "nz2",
    "classifyAlias" : "fg-nz2", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nz2.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(390),
    "name": "FG-女校高校足球队",
    "alias": "fg-nxzqd",
    "icon": "/common/gameIcon/fg/mobile/nzgxzqd.png",
    "url": "../nxzqd/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1981),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "nxzqd",
    "classifyAlias" : "fg-nxzqd", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/nzgxzqd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(391),
    "name": "FG-潘帕斯雄鹰",
    "alias": "fg-panpasixiongying",
    "icon": "/common/gameIcon/fg/mobile/panpasixiongying.png",
    "url": "../panpasixiongying/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1982),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "panpasixiongying",
    "classifyAlias" : "fg-panpasixiongying", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/panpasixiongying.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(392),
    "name": "FG-水果派对",
    "alias": "fg-party",
    "icon": "/common/gameIcon/fg/mobile/party.png",
    "url": "../party/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1983),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "party",
    "classifyAlias" : "fg-party", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/party.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(393),
    "name": "FG-抢红包",
    "alias": "fg-mqhb",
    "icon": "/common/gameIcon/fg/mobile/qhb.png",
    "url": "../mqhb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1984),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mqhb",
    "classifyAlias" : "fg-mqhb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/qhb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(394),
    "name": "FG-鹊桥会",
    "alias": "fg-qqh",
    "icon": "/common/gameIcon/fg/mobile/qqh.png",
    "url": "../qqh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1985),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "qqh",
    "classifyAlias" : "fg-qqh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/qqh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(395),
    "name": "FG-群星闪耀",
    "alias": "fg-qunxshanyao",
    "icon": "/common/gameIcon/fg/mobile/qunxshanyao.png",
    "url": "../qunxshanyao/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1986),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "qunxshanyao",
    "classifyAlias" : "fg-qunxshanyao", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/qunxshanyao.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(396),
    "name": "FG-七夕情缘",
    "alias": "fg-qxqy",
    "icon": "/common/gameIcon/fg/mobile/qxqy.png",
    "url": "../qxqy/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1987),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "qxqy",
    "classifyAlias" : "fg-qxqy", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/qxqy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(397),
    "name": "FG-抢庄牛牛3D",
    "alias": "fg-qznn3d",
    "icon": "/common/gameIcon/fg/mobile/qznn3d.png",
    "url": "../qznn3d/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1988),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "qznn3d",
    "classifyAlias" : "fg-qznn3d", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/qznn3d.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(398),
    "name": "FG-瑞狗迎春",
    "alias": "fg-rgyc",
    "icon": "/common/gameIcon/fg/mobile/rgyc.png",
    "url": "../rgyc/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1989),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "rgyc",
    "classifyAlias" : "fg-rgyc", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/rgyc.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(399),
    "name": "FG-人猿泰山",
    "alias": "fg-ryts",
    "icon": "/common/gameIcon/fg/mobile/ryts.png",
    "url": "../ryts/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1990),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "ryts",
    "classifyAlias" : "fg-ryts", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ryts.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(400),
    "name": "FG-荣耀王者",
    "alias": "fg-rywz",
    "icon": "/common/gameIcon/fg/mobile/rywz.png",
    "url": "../rywz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1991),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "rywz",
    "classifyAlias" : "fg-rywz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/rywz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(401),
    "name": "FG-四大美女",
    "alias": "fg-sdmn",
    "icon": "/common/gameIcon/fg/mobile/sdmn.png",
    "url": "../sdmn/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1992),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "sdmn",
    "classifyAlias" : "fg-sdmn", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sdmn.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(402),
    "name": "FG-神雕侠侣",
    "alias": "fg-wsdxl",
    "icon": "/common/gameIcon/fg/mobile/sdxl.png",
    "url": "../wsdxl/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1993),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wsdxl",
    "classifyAlias" : "fg-wsdxl", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sdxl.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(403),
    "name": "FG-水果机",
    "alias": "fg-frt",
    "icon": "/common/gameIcon/fg/mobile/sgj.png",
    "url": "../frt/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1994),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "frt",
    "classifyAlias" : "fg-frt", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sgj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(404),
    "name": "FG-水果转盘",
    "alias": "fg-fw",
    "icon": "/common/gameIcon/fg/mobile/sgzp.png",
    "url": "../fw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1995),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fw",
    "classifyAlias" : "fg-fw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sgzp.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(405),
    "name": "FG-世界杯吉祥物",
    "alias": "fg-sjbjxw",
    "icon": "/common/gameIcon/fg/mobile/sjbjxw.png",
    "url": "../sjbjxw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1996),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "sjbjxw",
    "classifyAlias" : "fg-sjbjxw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sjbjxw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(406),
    "name": "FG-世界末日",
    "alias": "fg-Doomsday",
    "icon": "/common/gameIcon/fg/mobile/sjmr.png",
    "url": "../Doomsday/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1997),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Doomsday",
    "classifyAlias" : "fg-Doomsday", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sjmr.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(407),
    "name": "FG-森林舞会",
    "alias": "fg-mslwh",
    "icon": "/common/gameIcon/fg/mobile/slwh.png",
    "url": "../mslwh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1998),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mslwh",
    "classifyAlias" : "fg-mslwh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/slwh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(408),
    "name": "FG-赛马",
    "alias": "fg-hr",
    "icon": "/common/gameIcon/fg/mobile/sm.png",
    "url": "../hr/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1999),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hr",
    "classifyAlias" : "fg-hr", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/sm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(409),
    "name": "FG-神秘东方",
    "alias": "fg-smdf",
    "icon": "/common/gameIcon/fg/mobile/smdf.png",
    "url": "../smdf/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2000),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "smdf",
    "classifyAlias" : "fg-smdf", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/smdf.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(410),
    "name": "FG-守望英雄",
    "alias": "fg-Watch",
    "icon": "/common/gameIcon/fg/mobile/swyx.png",
    "url": "../Watch/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2001),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Watch",
    "classifyAlias" : "fg-Watch", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/swyx.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(411),
    "name": "FG-淘金热",
    "alias": "fg-tjr",
    "icon": "/common/gameIcon/fg/mobile/tjr.png",
    "url": "../tjr/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2002),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "tjr",
    "classifyAlias" : "fg-tjr", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/tjr.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(412),
    "name": "FG-天龙八部",
    "alias": "fg-wtlbb",
    "icon": "/common/gameIcon/fg/mobile/tlbb.png",
    "url": "../wtlbb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2003),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wtlbb",
    "classifyAlias" : "fg-wtlbb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/tlbb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(413),
    "name": "FG-甜水绿洲",
    "alias": "fg-Lushwater",
    "icon": "/common/gameIcon/fg/mobile/tslz.png",
    "url": "../Lushwater/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2004),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Lushwater",
    "classifyAlias" : "fg-Lushwater", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/tslz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(414),
    "name": "FG-武松打虎",
    "alias": "fg-wsdf",
    "icon": "/common/gameIcon/fg/mobile/wsdh.png",
    "url": "../wsdf/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2005),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wsdf",
    "classifyAlias" : "fg-wsdf", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/wsdh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(415),
    "name": "FG-武圣关云长",
    "alias": "fg-wsgyc",
    "icon": "/common/gameIcon/fg/mobile/wsgyc.png",
    "url": "../wsgyc/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2006),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wsgyc",
    "classifyAlias" : "fg-wsgyc", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/wsgyc.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(416),
    "name": "FG-五星宏辉",
    "alias": "fg-wxhh",
    "icon": "/common/gameIcon/fg/mobile/wxhh.png",
    "url": "../wxhh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2007),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wxhh",
    "classifyAlias" : "fg-wxhh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/wxhh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(417),
    "name": "FG-笑傲江湖",
    "alias": "fg-wxajh",
    "icon": "/common/gameIcon/fg/mobile/xajh.png",
    "url": "../wxajh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2008),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wxajh",
    "classifyAlias" : "fg-wxajh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xajh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(418),
    "name": "FG-西部牛仔",
    "alias": "fg-nz",
    "icon": "/common/gameIcon/fg/mobile/xbnz.png",
    "url": "../nz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2009),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "nz",
    "classifyAlias" : "fg-nz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xbnz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(419),
    "name": "FG-现代战争",
    "alias": "fg-Mowf",
    "icon": "/common/gameIcon/fg/mobile/xdzz.png",
    "url": "../Mowf/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2010),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Mowf",
    "classifyAlias" : "fg-Mowf", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xdzz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(420),
    "name": "FG-仙剑",
    "alias": "fg-xj",
    "icon": "/common/gameIcon/fg/mobile/xj.png",
    "url": "../xj/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2011),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "xj",
    "classifyAlias" : "fg-xj", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(421),
    "name": "FG-剑侠情缘",
    "alias": "fg-jxqy",
    "icon": "/common/gameIcon/fg/mobile/xjqy.png",
    "url": "../jxqy/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2013),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jxqy",
    "classifyAlias" : "fg-jxqy", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xjqy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(422),
    "name": "FG-希腊传说",
    "alias": "fg-xlcs",
    "icon": "/common/gameIcon/fg/mobile/xlcs.png",
    "url": "../xlcs/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2014),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "xlcs",
    "classifyAlias" : "fg-xlcs", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xlcs.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(423),
    "name": "FG-新年符号",
    "alias": "fg-Nysymbols",
    "icon": "/common/gameIcon/fg/mobile/xnfh.png",
    "url": "../Nysymbols/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2015),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Nysymbols",
    "classifyAlias" : "fg-Nysymbols", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xnfh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(424),
    "name": "FG-吸血鬼PK狼人",
    "alias": "fg-xxgpklr",
    "icon": "/common/gameIcon/fg/mobile/xxgPKlr.png",
    "url": "../xxgpklr/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2016),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "xxgpklr",
    "classifyAlias" : "fg-xxgpklr", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xxgPKlr.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(425),
    "name": "FG-西游",
    "alias": "fg-xy",
    "icon": "/common/gameIcon/fg/mobile/xy.png",
    "url": "../xy/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2017),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "xy",
    "classifyAlias" : "fg-xy", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(426),
    "name": "FG-幸运5",
    "alias": "fg-lucky",
    "icon": "/common/gameIcon/fg/mobile/xy5.png",
    "url": "../lucky/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2018),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "lucky",
    "classifyAlias" : "fg-lucky", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xy5.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(427),
    "name": "FG-幸运水果机",
    "alias": "fg-mlfm",
    "icon": "/common/gameIcon/fg/mobile/xysgj.png",
    "url": "../mlfm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2019),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mlfm",
    "classifyAlias" : "fg-mlfm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/xysgj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(428),
    "name": "FG-印第安",
    "alias": "fg-yda",
    "icon": "/common/gameIcon/fg/mobile/yda.png",
    "url": "../yda/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2020),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "yda",
    "classifyAlias" : "fg-yda", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/yda.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(429),
    "name": "FG-招财进宝",
    "alias": "fg-zcjb",
    "icon": "/common/gameIcon/fg/mobile/zcjb.png",
    "url": "../zcjb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2021),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zcjb",
    "classifyAlias" : "fg-zcjb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zcjb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(430),
    "name": "FG-指环王",
    "alias": "fg-zhw",
    "icon": "/common/gameIcon/fg/mobile/zhw.png",
    "url": "../zhw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2022),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zhw",
    "classifyAlias" : "fg-zhw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zhw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(431),
    "name": "FG-战舰少女",
    "alias": "fg-zjsn",
    "icon": "/common/gameIcon/fg/mobile/zjsn.png",
    "url": "../zjsn/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2023),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zjsn",
    "classifyAlias" : "fg-zjsn", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zjsn.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(432),
    "name": "FG-侏罗纪公园",
    "alias": "fg-Jurassic",
    "icon": "/common/gameIcon/fg/mobile/zljgy.png",
    "url": "../Jurassic/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2024),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Jurassic",
    "classifyAlias" : "fg-Jurassic", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zljgy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(433),
    "name": "FG-湛蓝深海",
    "alias": "fg-xsjr",
    "icon": "/common/gameIcon/fg/mobile/zlsh.png",
    "url": "../xsjr/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2025),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "xsjr",
    "classifyAlias" : "fg-xsjr", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zlsh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(434),
    "name": "FG-中世纪特权",
    "alias": "fg-zsjtq",
    "icon": "/common/gameIcon/fg/mobile/zsjtq.png",
    "url": "../zsjtq/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2026),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zsjtq",
    "classifyAlias" : "fg-zsjtq", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zsjtq.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(435),
    "name": "FG-钻石之恋",
    "alias": "fg-mdl",
    "icon": "/common/gameIcon/fg/mobile/zszl.png",
    "url": "../mdl/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2027),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mdl",
    "classifyAlias" : "fg-mdl", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zszl.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(436),
    "name": "FG-众神之王",
    "alias": "fg-mmm",
    "icon": "/common/gameIcon/fg/mobile/zszw.png",
    "url": "../mmm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2028),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mmm",
    "classifyAlias" : "fg-mmm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zszw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(437),
    "name": "FG-植物大战僵尸",
    "alias": "fg-PVZ",
    "icon": "/common/gameIcon/fg/mobile/zwdzjs.png",
    "url": "../PVZ/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2029),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "PVZ",
    "classifyAlias" : "fg-PVZ", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zwdzjs.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(438),
    "name": "FG-自由女神",
    "alias": "fg-Pinup",
    "icon": "/common/gameIcon/fg/mobile/zyns.png",
    "url": "../Pinup/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2030),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Pinup",
    "classifyAlias" : "fg-Pinup", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zyns.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(439),
    "name": "FG-战争",
    "alias": "fg-zz",
    "icon": "/common/gameIcon/fg/mobile/zz.png",
    "url": "../zz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2031),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zz",
    "classifyAlias" : "fg-zz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(440),
    "name": "FG-蜘蛛侠",
    "alias": "fg-zzx",
    "icon": "/common/gameIcon/fg/mobile/zzx.png",
    "url": "../zzx/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(2032),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zzx",
    "classifyAlias" : "fg-zzx", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/zzx.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
}
];


// 删除基本表中的游戏数据
function removeOldData(oldGameName){
	db.brand.update({},{$pull: {"games": {"gameName":oldGameName,classify:3} }},{multi:true});
	db.base_game_config.remove({"name":oldGameName,classify:3},false);
}

/*初始化业主游戏信息*/
function initBrandGameInfo(gameId) {
    var brandList = db.brand.distinct("brand");
    print("现有游戏业主: " + brandList);
    print("开始初始化业主游戏信息");

    for (var i = 0; i < brandList.length; i++) {
        var brand = brandList[i];
        var gameInfo = db.base_game_config.findOne({ _id: gameId });
        var brandGameInfo = {};
        brandGameInfo.gameId = NumberInt(gameInfo._id);
        brandGameInfo.gameName = gameInfo.name;
        brandGameInfo.state = "NORMAL";
        brandGameInfo.sort = NumberInt(gameInfo.sort);
		brandGameInfo.classify = NumberInt(gameInfo.classify);
		brandGameInfo.classifyStatus = gameInfo.classifyStatus;
		brandGameInfo.classifyGameIds = gameInfo.classifyGameIds;
		brandGameInfo.gamePlatform = gameInfo.gamePlatform;
		brandGameInfo.classifyOnlineFlag = gameInfo.classifyOnlineFlag;
		brandGameInfo.classifySort = NumberInt(gameInfo.classifySort);
		brandGameInfo.enterLimit = NumberInt(gameInfo.enterLimit);
        brandGameInfo.createTime = new Date();
        brandGameInfo.updateTime = new Date();
        brandGameInfo.rooms = [];
        print("插入对应的游戏数据");
        printjson(brandGameInfo);
        db.brand.update({ "brand": brand }, { $addToSet: { "games": brandGameInfo } });
    }
}
games.forEach(game => {
	removeOldData(game.name);
	print(game.name+" remove success")
});

db.base_game_config.insert(games);
games.forEach(game => {
    initBrandGameInfo(game._id);
});