var games = [{
    "_id": NumberInt(301),
    "name": "FG-十二生肖",
    "alias": "fg-Zodiac",
    "icon": "/common/gameIcon/fg/mobile/12sx.png",
    "url": "../s004_Zodiac/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1891),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Zodiac",
    "classifyAlias" : "fg-Zodiac", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(1), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/12sx.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(302),
    "name": "FG-十二星座",
    "alias": "fg-Constellation",
    "icon": "/common/gameIcon/fg/mobile/12xz.png",
    "url": "../s004_fg-Constellation/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1892),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Constellation",
    "classifyAlias" : "fg-Constellation", 
    "classifyStatus" : "NORMAL",
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(2), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/12xz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(303),
    "name": "FG-66路",
    "alias": "fg-Route66",
    "icon": "/common/gameIcon/fg/mobile/66l.png",
    "url": "../s004_Route66/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1893),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Route66",
    "classifyAlias" : "fg-Route66", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(3), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/66l.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(304),
    "name": "FG-80天旅行",
    "alias": "fg-80tlx",
    "icon": "/common/gameIcon/fg/mobile/80tlx.png",
    "url": "../s004_fg-80tlx/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1894),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "80tlx",
    "classifyAlias" : "fg-80tlx", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(4), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/80tlx.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(305),
    "name": "FG-阿凡达",
    "alias": "fg-Avatar",
    "icon": "/common/gameIcon/fg/mobile/afd.png",
    "url": "../s004_fg-Avatar/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1895),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Avatar",
    "classifyAlias" : "fg-Avatar", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(5), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/afd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(306),
    "name": "FG-埃菲尔",
    "alias": "fg-Eiffel",
    "icon": "/common/gameIcon/fg/mobile/afe.png",
    "url": "../s004_fg-Eiffel/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1896),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Eiffel",
    "classifyAlias" : "fg-Eiffel", 
    "classifyStatus" : "NORMAL",
	"enterLimit" : NumberInt(10),	
    "classifySort" : NumberInt(6), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/afe.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(307),
    "name": "FG-埃及",
    "alias": "fg-Egypt",
    "icon": "/common/gameIcon/fg/mobile/aj.png",
    "url": "../s004_fg-Egypt/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1897),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Egypt",
    "classifyAlias" : "fg-Egypt", 
    "classifyStatus" : "NORMAL",
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(7), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/aj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(308),
    "name": "FG-埃及女王",
    "alias": "fg-aijinw",
    "icon": "/common/gameIcon/fg/mobile/ajnw.png",
    "url": "../s004_fg-aijinw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1898),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "aijinw",
    "classifyAlias" : "fg-aijinw", 
    "classifyStatus" : "NORMAL",
	"enterLimit" : NumberInt(10),	
    "classifySort" : NumberInt(8), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ajnw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(309),
    "name": "FG-阿兹特克",
    "alias": "fg-azteke",
    "icon": "/common/gameIcon/fg/mobile/aztk.png",
    "url": "../s004_fg-azteke/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1899),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "azteke",
    "classifyAlias" : "fg-azteke", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(9), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/aztk.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(310),
    "name": "FG-奔驰宝马",
    "alias": "fg-bzb",
    "icon": "/common/gameIcon/fg/mobile/bcbm.png",
    "url": "../s004_fg-bzb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1900),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "bzb",
    "classifyAlias" : "fg-bzb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(10), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/bcbm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(311),
    "name": "FG-奔驰宝马2",
    "alias": "fg-bcbm",
    "icon": "/common/gameIcon/fg/mobile/bcbm2.png",
    "url": "../s004_fg-bcbm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1901),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "bcbm",
    "classifyAlias" : "fg-bcbm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(11), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/bcbm2.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(312),
    "name": "FG-21点",
    "alias": "fg-bj",
    "icon": "/common/gameIcon/fg/mobile/bj.png",
    "url": "../s004_fg-bj/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1902),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "bj",
    "classifyAlias" : "fg-bj", 
    "classifyStatus" : "NORMAL",
	"enterLimit" : NumberInt(10),	
    "classifySort" : NumberInt(12), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/bj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(313),
    "name": "FG-白蛇传",
    "alias": "fg-bsz",
    "icon": "/common/gameIcon/fg/mobile/bsz.png",
    "url": "../s004_fg-bsz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1903),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "bsz",
    "classifyAlias" : "fg-bsz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(13), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/bsz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(314),
    "name": "FG-变形金刚",
    "alias": "fg-bxjg",
    "icon": "/common/gameIcon/fg/mobile/bxjg.png",
    "url": "../s004_fg-bxjg/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1904),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "bxjg",
    "classifyAlias" : "fg-bxjg", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(14), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/bxjg.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(315),
    "name": "FG-捕鱼达人",
    "alias": "fg-Fishing",
    "icon": "/common/gameIcon/fg/mobile/bydr.png",
    "url": "../s004_fg-Fishing/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1905),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Fishing",
    "classifyAlias" : "fg-Fishing", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(15), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/bydr.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(316),
    "name": "FG-刺客信条",
    "alias": "fg-ckxt",
    "icon": "/common/gameIcon/fg/mobile/ckxt.png",
    "url": "../s004_fg-ckxt/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1906),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "ckxt",
    "classifyAlias" : "fg-ckxt", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(16), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ckxt.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(317),
    "name": "FG-糖果派对",
    "alias": "fg-cp",
    "icon": "/common/gameIcon/fg/mobile/cp.png",
    "url": "../s004_fg-cp/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1907),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "cp",
    "classifyAlias" : "fg-cp", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(17), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/cp.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(318),
    "name": "FG-多福多财",
    "alias": "fg-dfdc",
    "icon": "/common/gameIcon/fg/mobile/dfdc.png",
    "url": "../s004_fg-dfdc/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1908),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "dfdc",
    "classifyAlias" : "fg-dfdc", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/dfdc.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(319),
    "name": "FG-东方国度",
    "alias": "fg-zgf",
    "icon": "/common/gameIcon/fg/mobile/dfgd.png",
    "url": "../s004_fg-zgf/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1909),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "zgf",
    "classifyAlias" : "fg-zgf", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/dfgd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(320),
    "name": "FG-大秦帝国",
    "alias": "fg-dqdg",
    "icon": "/common/gameIcon/fg/mobile/dqdg.png",
    "url": "../s004_fg-dqdg/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1910),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "dqdg",
    "classifyAlias" : "fg-dqdg", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/dqdg.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(321),
    "name": "FG-哪吒闹海",
    "alias": "fg-nznh",
    "icon": "/common/gameIcon/fg/mobile/eznh.png",
    "url": "../s004_fg-nznh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1911),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "nznh",
    "classifyAlias" : "fg-nznh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/eznh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(322),
    "name": "FG-速度與激情",
    "alias": "fg-fastf",
    "icon": "/common/gameIcon/fg/mobile/fastf.png",
    "url": "../s004_fg-fastf/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1912),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fastf",
    "classifyAlias" : "fg-fastf", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fastf.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(323),
    "name": "FG-浮岛历险记",
    "alias": "fg-fia",
    "icon": "/common/gameIcon/fg/mobile/fdlxj.png",
    "url": "../s004_fg-fia/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1913),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fia",
    "classifyAlias" : "fg-fia", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fdlxj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(324),
    "name": "FG-发发发",
    "alias": "fg-fff",
    "icon": "/common/gameIcon/fg/mobile/fff.png",
    "url": "../s004_fg-fff/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1914),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fff",
    "classifyAlias" : "fg-fff", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fff.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(325),
    "name": "FG-粉红女郎",
    "alias": "fg-mpg",
    "icon": "/common/gameIcon/fg/mobile/fhnl.png",
    "url": "../s004_fg-mpg/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1915),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mpg",
    "classifyAlias" : "fg-mpg", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fhnl.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(326),
    "name": "FG-美人鱼传说",
    "alias": "fg-fish_mrycs",
    "icon": "/common/gameIcon/fg/mobile/fish_mrycs.png",
    "url": "../s004_fg-fish_mrycs/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1916),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fish_mrycs",
    "classifyAlias" : "fg-fish_mrycs", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fish_mrycs.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(327),
    "name": "FG-水果传奇",
    "alias": "fg-fl",
    "icon": "/common/gameIcon/fg/mobile/fl.png",
    "url": "../s004_fg-fl/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1917),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fl",
    "classifyAlias" : "fg-fl", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fl.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(328),
    "name": "FG-愤怒的小鸟",
    "alias": "fg-Angrybirds",
    "icon": "/common/gameIcon/fg/mobile/fndxn.png",
    "url": "../s004_Angrybirds/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1918),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Angrybirds",
    "classifyAlias" : "fg-Angrybirds", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fndxn.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(329),
    "name": "FG-飞禽走兽",
    "alias": "fg-bbs",
    "icon": "/common/gameIcon/fg/mobile/fqzs.png",
    "url": "../bbs/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1919),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "bbs",
    "classifyAlias" : "fg-bbs", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fqzs.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(330),
    "name": "FG-富饶农场",
    "alias": "fg-frnc",
    "icon": "/common/gameIcon/fg/mobile/frnc.png",
    "url": "../frnc/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1920),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "frnc",
    "classifyAlias" : "fg-frnc", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/frnc.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(331),
    "name": "FG-封神榜",
    "alias": "fg-fsb",
    "icon": "/common/gameIcon/fg/mobile/fsb.png",
    "url": "../fsb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1921),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "fsb",
    "classifyAlias" : "fg-fsb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/fsb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(332),
    "name": "FG-格斗之王",
    "alias": "fg-gdzw",
    "icon": "/common/gameIcon/fg/mobile/gdzw.png",
    "url": "../gdzw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1922),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "gdzw",
    "classifyAlias" : "fg-gdzw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/gdzw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(333),
    "name": "FG-功夫熊猫",
    "alias": "fg-Panda",
    "icon": "/common/gameIcon/fg/mobile/gfxm.png",
    "url": "../Panda/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1923),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Panda",
    "classifyAlias" : "fg-Panda", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/gfxm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(334),
    "name": "FG-关秦龙虎斗",
    "alias": "fg-ggdqq",
    "icon": "/common/gameIcon/fg/mobile/ggdqq.png",
    "url": "../ggdqq/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1924),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "ggdqq",
    "classifyAlias" : "fg-ggdqq", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ggdqq.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(335),
    "name": "FG-古怪猴子",
    "alias": "fg-gghz",
    "icon": "/common/gameIcon/fg/mobile/gghz.png",
    "url": "../gghz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1925),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "gghz",
    "classifyAlias" : "fg-gghz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/gghz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(336),
    "name": "FG-恭贺新春",
    "alias": "fg-ghxc",
    "icon": "/common/gameIcon/fg/mobile/ghxc.png",
    "url": "../ghxc/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1926),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "ghxc",
    "classifyAlias" : "fg-ghxc", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ghxc.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(337),
    "name": "FG-灌篮高手",
    "alias": "fg-msd",
    "icon": "/common/gameIcon/fg/mobile/glgs.png",
    "url": "../msd/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1927),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "msd",
    "classifyAlias" : "fg-msd", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/glgs.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(338),
    "name": "FG-古墓丽影",
    "alias": "fg-gmly",
    "icon": "/common/gameIcon/fg/mobile/gmly.png",
    "url": "../gmly/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1928),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "gmly",
    "classifyAlias" : "fg-gmly", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/gmly.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(339),
    "name": "FG-哥谭魅影",
    "alias": "fg-gtmymn",
    "icon": "/common/gameIcon/fg/mobile/gtmy.png",
    "url": "../gtmymn/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1929),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "gtmymn",
    "classifyAlias" : "fg-gtmymn", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/gtmy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(340),
    "name": "FG-怪物命运",
    "alias": "fg-gwmy",
    "icon": "/common/gameIcon/fg/mobile/gwmy.png",
    "url": "../gwmy/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1930),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "gwmy",
    "classifyAlias" : "fg-gwmy", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/gwmy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(341),
    "name": "FG-海盗财富",
    "alias": "fg-hdcf",
    "icon": "/common/gameIcon/fg/mobile/hdcf.png",
    "url": "../hdcf/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1931),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hdcf",
    "classifyAlias" : "fg-hdcf", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hdcf.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(342),
    "name": "FG-黄金大转轮",
    "alias": "fg-gw",
    "icon": "/common/gameIcon/fg/mobile/hjdzl.png",
    "url": "../gw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1932),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "gw",
    "classifyAlias" : "fg-gw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hjdzl.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(343),
    "name": "FG-黄金右脚",
    "alias": "fg-hjyj",
    "icon": "/common/gameIcon/fg/mobile/hjyj.png",
    "url": "../hjyj/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1933),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hjyj",
    "classifyAlias" : "fg-hjyj", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hjyj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(344),
    "name": "FG-红楼梦",
    "alias": "fg-hlm",
    "icon": "/common/gameIcon/fg/mobile/hlm.png",
    "url": "../hlm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1934),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hlm",
    "classifyAlias" : "fg-hlm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hlm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(345),
    "name": "FG-欢乐麻将3D",
    "alias": "fg-hlmj3D",
    "icon": "/common/gameIcon/fg/mobile/hlmj3D.png",
    "url": "../hlmj3D/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1935),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hlmj3D",
    "classifyAlias" : "fg-hlmj3D", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hlmj3D.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(346),
    "name": "FG-欢乐水果",
    "alias": "fg-sg",
    "icon": "/common/gameIcon/fg/mobile/hlsg.png",
    "url": "../sg/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1936),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "sg",
    "classifyAlias" : "fg-sg", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hlsg.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(347),
    "name": "FG-幻想大陆",
    "alias": "fg-hxdl",
    "icon": "/common/gameIcon/fg/mobile/hxdl.png",
    "url": "../hxdl/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1937),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hxdl",
    "classifyAlias" : "fg-hxdl", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hxdl.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(348),
    "name": "FG-火影忍者",
    "alias": "fg-hyrz",
    "icon": "/common/gameIcon/fg/mobile/hyrz.png",
    "url": "../hyrz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1938),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hyrz",
    "classifyAlias" : "fg-hyrz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hyrz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(349),
    "name": "FG-猴子爬树",
    "alias": "fg-mr",
    "icon": "/common/gameIcon/fg/mobile/hzps.png",
    "url": "../mr/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1939),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mr",
    "classifyAlias" : "fg-mr", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hzps.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(350),
    "name": "FG-黑珍珠号",
    "alias": "fg-hzzh",
    "icon": "/common/gameIcon/fg/mobile/hzzh.png",
    "url": "../hzzh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1940),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "hzzh",
    "classifyAlias" : "fg-hzzh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/hzzh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(351),
    "name": "FG-角斗士",
    "alias": "fg-jiaods",
    "icon": "/common/gameIcon/fg/mobile/jds.png",
    "url": "../jiaods/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1941),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jiaods",
    "classifyAlias" : "fg-jiaods", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jds.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(352),
    "name": "FG-金刚",
    "alias": "fg-jg",
    "icon": "/common/gameIcon/fg/mobile/jg.png",
    "url": "../jg/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1942),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jg",
    "classifyAlias" : "fg-jg", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jg.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(353),
    "name": "FG-红黑大战",
    "alias": "fg-rbwars",
    "icon": "/common/gameIcon/fg/mobile/jgf.png",
    "url": "../rbwars/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1943),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jgf",
    "classifyAlias" : "fg-rbwars", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jgf.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(354),
    "name": "FG-金狗旺财",
    "alias": "fg-jgwc",
    "icon": "/common/gameIcon/fg/mobile/jgwc.png",
    "url": "../jgwc/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1944),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jgwc",
    "classifyAlias" : "fg-jgwc", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jgwc.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(355),
    "name": "FG-加勒比海盗",
    "alias": "fg-Pirates",
    "icon": "/common/gameIcon/fg/mobile/jlbhd.png",
    "url": "../Pirates/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1945),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "Pirates",
    "classifyAlias" : "fg-Pirates", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jlbhd.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(356),
    "name": "FG-金瓶梅",
    "alias": "fg-jpm",
    "icon": "/common/gameIcon/fg/mobile/jpm.png",
    "url": "../jpm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1946),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jpm",
    "classifyAlias" : "fg-jpm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jpm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(357),
    "name": "FG-激情世界杯",
    "alias": "fg-mjqsjb",
    "icon": "/common/gameIcon/fg/mobile/jqsjb.png",
    "url": "../mjqsjb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1947),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mjqsjb",
    "classifyAlias" : "fg-mjqsjb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jqsjb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(358),
    "name": "FG-金球争霸",
    "alias": "fg-jqzb",
    "icon": "/common/gameIcon/fg/mobile/jqzb.png",
    "url": "../jqzb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1948),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jqzb",
    "classifyAlias" : "fg-jqzb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jqzb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(359),
    "name": "FG-金靴争霸",
    "alias": "fg-mjxzb",
    "icon": "/common/gameIcon/fg/mobile/jszb.png",
    "url": "../mjxzb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1949),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mjxzb",
    "classifyAlias" : "fg-mjxzb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jszb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(360),
    "name": "FG-街头霸王",
    "alias": "fg-jtbw",
    "icon": "/common/gameIcon/fg/mobile/jtbw.png",
    "url": "../jtbw/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1950),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "jtbw",
    "classifyAlias" : "fg-jtbw", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/jtbw.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(361),
    "name": "FG-狂欢",
    "alias": "fg-kh",
    "icon": "/common/gameIcon/fg/mobile/kh.png",
    "url": "../kh/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1951),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "kh",
    "classifyAlias" : "fg-kh", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/kh.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(362),
    "name": "FG-鹿鼎记",
    "alias": "fg-wldj",
    "icon": "/common/gameIcon/fg/mobile/ldj.png",
    "url": "../wldj/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1952),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wldj",
    "classifyAlias" : "fg-wldj", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ldj.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(363),
    "name": "FG-乐斗牛魔王3D",
    "alias": "fg-ldnmw3D",
    "icon": "/common/gameIcon/fg/mobile/ldnmw3D.png",
    "url": "../ldnmw3D/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1953),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "ldnmw3D",
    "classifyAlias" : "fg-ldnmw3D", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/ldnmw3D.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(364),
    "name": "FG-连环夺宝",
    "alias": "fg-si",
    "icon": "/common/gameIcon/fg/mobile/lhdb.png",
    "url": "../si/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1954),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "si",
    "classifyAlias" : "fg-si", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/lhdb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(365),
    "name": "FG-啦啦队",
    "alias": "fg-scs",
    "icon": "/common/gameIcon/fg/mobile/lld.png",
    "url": "../scs/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1955),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "scs",
    "classifyAlias" : "fg-scs", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/lld.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(366),
    "name": "FG-拉斯维加斯",
    "alias": "fg-wjs",
    "icon": "/common/gameIcon/fg/mobile/lswjs.png",
    "url": "../wjs/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1956),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "wjs",
    "classifyAlias" : "fg-wjs", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/lswjs.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(367),
    "name": "FG-绿野仙踪",
    "alias": "fg-lyxz",
    "icon": "/common/gameIcon/fg/mobile/lyxz.png",
    "url": "../lyxz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1957),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "lyxz",
    "classifyAlias" : "fg-lyxz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/lyxz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(368),
    "name": "FG-龙珠探宝",
    "alias": "fg-lztb",
    "icon": "/common/gameIcon/fg/mobile/lztb.png",
    "url": "../lztb/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1958),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "lztb",
    "classifyAlias" : "fg-lztb", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/lztb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(369),
    "name": "FG-街机水浒传",
    "alias": "fg-mawm",
    "icon": "/common/gameIcon/fg/mobile/mawm.png",
    "url": "../mawm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1959),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mawm",
    "classifyAlias" : "fg-mawm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mawm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(370),
    "name": "FG-海岛奇兵",
    "alias": "fg-mboombeach",
    "icon": "/common/gameIcon/fg/mobile/mboombeach.png",
    "url": "../mboombeach/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1960),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mboombeach",
    "classifyAlias" : "fg-mboombeach", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mboombeach.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(371),
    "name": "FG-萌宠夺宝",
    "alias": "fg-api",
    "icon": "/common/gameIcon/fg/mobile/mcdb.png",
    "url": "../api/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1961),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "api",
    "classifyAlias" : "fg-api", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mcdb.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(372),
    "name": "FG-百变猴子",
    "alias": "fg-mcm",
    "icon": "/common/gameIcon/fg/mobile/mcm.png",
    "url": "../mcm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1962),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mcm",
    "classifyAlias" : "fg-mcm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mcm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(373),
    "name": "FG-疯狂七",
    "alias": "fg-mcrazy7",
    "icon": "/common/gameIcon/fg/mobile/mcrazy7.png",
    "url": "../mcrazy7/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1963),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mcrazy7",
    "classifyAlias" : "fg-mcrazy7", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mcrazy7.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(374),
    "name": "FG-船长宝藏",
    "alias": "fg-mczbz",
    "icon": "/common/gameIcon/fg/mobile/mczbz.png",
    "url": "../mczbz/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1964),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mczbz",
    "classifyAlias" : "fg-mczbz", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mczbz.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(375),
    "name": "FG-梦幻西游",
    "alias": "fg-mhxy",
    "icon": "/common/gameIcon/fg/mobile/mhxy.png",
    "url": "../mhxy/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1965),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mhxy",
    "classifyAlias" : "fg-mhxy", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mhxy.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
},
{
    "_id": NumberInt(376),
    "name": "FG-激情球迷",
    "alias": "fg-mjqqm",
    "icon": "/common/gameIcon/fg/mobile/mjqqm.png",
    "url": "../mjqqm/",
    "jumpUrl": true,
    "gameStyle": "CARD_GAME",
    "state": "NORMAL",
    "sort": NumberInt(1966),
    "retryConnection": false,
    "createTime": new Date(),
    "updateTime": new Date(),
    "rooms":[],
	"gamePlatform": "FG",
	"classify" : NumberInt(3), 
	"classifyThirdGameId": "mjqqm",
    "classifyAlias" : "fg-mjqqm", 
    "classifyStatus" : "NORMAL", 
	"enterLimit" : NumberInt(10),
    "classifySort" : NumberInt(18), 
    "classifyIcon" : "/common/gameIcon/fg/mobile/mjqqm.png",
	"classifyGameIds" : "", 
    "classifyGames" : [], 
    "classifyOnlineFlag" : true
}
];


// 删除基本表中的游戏数据
function removeOldData(oldGameName){
	db.brand.update({},{$pull: {"games": {"gameName":oldGameName,classify:3} }},{multi:true});
	db.base_game_config.remove({"name":oldGameName,classify:3},false);
}

/*初始化业主游戏信息*/
function initBrandGameInfo(gameId) {
    var brandList = db.brand.distinct("brand");
    print("现有游戏业主: " + brandList);
    print("开始初始化业主游戏信息");

    for (var i = 0; i < brandList.length; i++) {
        var brand = brandList[i];
        var gameInfo = db.base_game_config.findOne({ _id: gameId });
        var brandGameInfo = {};
        brandGameInfo.gameId = NumberInt(gameInfo._id);
        brandGameInfo.gameName = gameInfo.name;
        brandGameInfo.state = "NORMAL";
        brandGameInfo.sort = NumberInt(gameInfo.sort);
		brandGameInfo.classify = NumberInt(gameInfo.classify);
		brandGameInfo.classifyStatus = gameInfo.classifyStatus;
		brandGameInfo.classifyGameIds = gameInfo.classifyGameIds;
		brandGameInfo.gamePlatform = gameInfo.gamePlatform;
		brandGameInfo.classifyOnlineFlag = gameInfo.classifyOnlineFlag;
		brandGameInfo.classifySort = NumberInt(gameInfo.classifySort);
		brandGameInfo.enterLimit = NumberInt(gameInfo.enterLimit);
        brandGameInfo.createTime = new Date();
        brandGameInfo.updateTime = new Date();
        brandGameInfo.rooms = [];
        print("插入对应的游戏数据");
        printjson(brandGameInfo);
        db.brand.update({ "brand": brand }, { $addToSet: { "games": brandGameInfo } });
    }
}
games.forEach(game => {
	removeOldData(game.name);
	print(game.name+" remove success")
});

db.base_game_config.insert(games);
games.forEach(game => {
    initBrandGameInfo(game._id);
});