spring:
  application:
    name: game-envelop-app
  profiles:
    active: pro
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: GMT+8
  redis:
    host: 192.168.1.57
    database: 7
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 30000
        min-idle: 1
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://sec_game:1qaz2wsx@192.168.1.96:20000,192.168.1.97:20000,192.168.1.98:20000
      database: game
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: game_center_app
    password: Jxinternet@1234
    url: jdbc:mysql://192.168.1.93:3306/gcenter?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true

logging:
  config: classpath:logback-spring.xml

server:
  port: 8099

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus

rocket:
  namesrv-address: 192.168.1.157:9876;192.168.1.158:9876
  consumer-group: hlhb_consumer_group
  consumer-topic: cg_hlhb_in
  producer-group: hlhb_producer_group
  producer-topic: cg_hlhb_out
  system_group: game_interior_consumer_group
  system_topic: game_interior_in

customer:
  datasource:
    gCenter:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/gcenter?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: game_center_app
      password: Jxinternet@1234
    masterDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234
    slaveDataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.93:3306/balance?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: sec_balance
      password: Jxinternet@1234

game:
  id: 26
  name: 欢乐红包
  table-cache-second: 900
  show_bet_num_timeout: 3500
  wait_size_timeout: 4000
  final_size_timeout: 1000
  dice_timeout: 3500
  settlement_timeout: 5000
  next_timeout: 2000
  wait_bet_timeout: 3000
  count_timeout: 1000

  match:
    wait-queue-capacity: 50
    threads: 2
    max-wait-seconds: 5
    max-person: 5
  timeout:
    wait-queue-capacity: 100
    threads: 2
    batch-tasks: 5
